#!/bin/bash

if [ -r ./common ]; then
    . common
elif [ -r ~/peat-scripts/testrun/common ]; then
    . ~/peat-scripts/testrun/common
fi

[ -z ${PNBIN} ] && { echo "Can't find peat-node binary. Stop"; exit 1; }

mkdir -p ${HOME}/peat-testrun
cd ${HOME}/peat-testrun

#${PNBIN} --listen ${EXTIP}:${TCPP} --shared-key ${SHKEY} ${DDIR} --auto-sync --node-id ${NID} --iroh-udp-port 51081 ${PEERS} --app-id ${APPID}

${PNBIN}

cd ${CWD}
