#!/bin/bash

if [ -r ./common ]; then
    . common
elif [ -r ~/peat-scripts/testrun/common ]; then
    . ~/peat-scripts/testrun/common
fi


if [ -d ${HOME}/prj/esl/peat-node ]; then
  cd ${HOME}/prj/esl/peat-node
  git pull
elif [ ! -d ${HOME}/peat-node ]; then
  cd
  git clone https://github.com/defenseunicorns/peat-node.git
  cd peat-node
else
  cd ${HOME}/peat-node
  git pull
fi

export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C link-arg=-fuse-ld=mold"
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="clang"

cargo build --release
check_rc "cargo build --release"

cargo build -p peat-cli --release
check_rc "build -p peat-cli"

# only on Arch Linux (test laptop)
if [ "_`hostname`" == "_hpprobook6570b" ]; then
  unset CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS
  unset CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER
  cross build --release --target aarch64-unknown-linux-gnu
  check_rc "cross build"
  cross build -p peat-cli --release --target aarch64-unknown-linux-gnu
  check_rc "cross build -p peat-cli"
fi

unset CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS
unset CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER

cd ${CWD}
